########################################################
#                    endPoints peliculas               #
########################################################
GET http://localhost:3001/movie/


###

GET http://localhost:3001/movie/id/5dcc325de4a8fd83e208c8c0

###

GET http://localhost:3001/movie/title/avengers
###

GET http://localhost:3001/movie/genre/drama



########################################################
#                    endPoints users                   #
########################################################



POST http://localhost:3001/user/register
Content-Type: application/json

{
    "username": "maria",
    "password":"58412",
    "email": "esteban@gmail.com"
}


###

PATCH http://localhost:3001/user/login
Content-Type: application/json

{
    "username": "maria",
    "password":"58412"
}

###

PATCH http://localhost:3001/user/logout
Content-Type: application/json

{
    "username": "esteban",
    "password":"58412"
}

###

GET http://localhost:3001/user/profile
Authorization:  5dd6ed4d771286301c937189

########################################################
#                    endPoints pedidos                 #
########################################################


PATCH  http://localhost:3001/user/profile/order
Authorization:  5dd6ed4d771286301c937189
Content-Type: application/json

{
    "title": "spiderman"
}

###

PATCH http://localhost:3001/user/profile/order/cancel
Authorization: 5dd5bf8104646c3c146decdf

###

POST  http://localhost:3001/user/profile/viewed
Authorization: 5dd5bf8104646c3c146decdf

###

POST http://localhost:3001/user/profile/views/vote
Authorization: 5dd5739eba955f1b48c88783







