########################################################
#                    endPoints peliculas               #
########################################################
GET http://localhost:3001/movie


###

GET http://localhost:3001/movie/id/5dcc325de4a8fd83e208c8c0

###

GET http://localhost:3001/movie/title/vengadores

###

GET http://localhost:3001/movie/genre/action


########################################################
#                    endPoints users                   #
########################################################



POST http://localhost:3001/user/register
Content-Type: application/json

{
    "username": "manuel",
    "password":"10234"
}


###

PATCH http://localhost:3001/user/login
Content-Type: application/json

{
    "username": "manuel",
    "password":"10234"
}

###

PATCH http://localhost:3001/user/logout
Content-Type: application/json

{
    "username": "manuel",
    "password":"10234"
}

###

GET http://localhost:3001/user/profile
Authorization: 5dd2bc17e071f501bc70e2c1


########################################################
#                    endPoints pedidos                 #
########################################################


post http://localhost:3001/user/profile/order
Authorization: 5dd2bc17e071f501bc70e2c1
Content-Type: application/json

{
    "title": "avengers"
}








