########################################################
#                    endPoints peliculas               #
########################################################
GET http://localhost:3001/movie/


###

GET http://localhost:3001/movie/id/5dcc325de4a8fd83e208c8c0

###

GET http://localhost:3001/movie/title/avengers

###

GET http://localhost:3001/movie/genre/comedia



########################################################
#                    endPoints users                   #
########################################################



POST http://localhost:3001/user/register
Content-Type: application/json

{
    "username": "maria",
    "password":"12345678",
    "email": "manolo@gmail.com"
}


###

PATCH http://localhost:3001/user/login
Content-Type: application/json

{
    "username": "manolo",
    "password":"12345678"
}

###

PATCH http://localhost:3001/user/logout
Authorization: 5dd7e20851956c241c4d5700
###

GET http://localhost:3001/user/profile
Authorization: 5ddaf7e9c142b01b68ef7a08
########################################################
#                    endPoints pedidos                 #
########################################################


PATCH  http://localhost:3001/user/profile/order
Authorization:  5ddb99a96777c71030cf04fb
Content-Type: application/json

{
    "title": "terminator",
    "numberRentingDays": "15"
}

###

PATCH http://localhost:3001/user/profile/order/cancel
Authorization: 5ddb99a96777c71030cf04fb

###

GET http://localhost:3001/user/profile/viewed
Authorization: 5dd7e57031d78316b896d0d4

###


########################################################
#                    endPoints admin                   #
########################################################



POST    http://localhost:3001/user/admin/insertFilm
Authorization:   5ddaf7e9c142b01b68ef7a08
Content-Type: application/json

{
    "original_title": "Fantastic Beasts: The Crimes of Grindelwald",
    "poster_path": "/uDE3WV0X75NAxHCubGQY1MHoWIO.jpg",
    "id": "338952",
    "genre_ids": [12, 14, 10751],
    "title": "Animales fantásticos: los crímenes de Grindelwald",
    "release_date": "2018-11-14" 
}

###


DELETE http://localhost:3001/user/admin/removeFilm
Authorization:   5dd7e57031d78316b896d0d4
Content-Type: application/json

{
    "title": "Animales fantásticos: los crímenes de Grindelwald"
}

###

PATCH   http://localhost:3001/user/admin/setAdmin
Authorization:   5ddaf7e9c142b01b68ef7a08
Content-Type: application/json

{
    "username": "perico",
    "admin": "true"
}

###








